[project]
name = "cryptography-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcrypt>=5.0.0",
    "cryptography>=46.0.3",
    "zxcvbn>=4.5.0",
]
